version: '3'

services:
  flaskapp:
    build: ./flaskapp-docker
    image: flaskapp:latest
    container_name: learnflask
    network_mode: host

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: learnnginx
    network_mode: host
